from __future__ import annotations

from . import catalogue_fixes, main, tv_main

app = tv_main.app

_TV_UI = r"""
<style>
  .media-switch{display:inline-flex;gap:4px;padding:4px;border:1px solid var(--border);border-radius:14px;background:#0d1119;margin:22px 0 0}.media-switch button{border:0;background:transparent;color:var(--muted);padding:9px 15px;border-radius:10px;font-weight:850}.media-switch button.active{background:var(--surface-2);color:var(--text)}
  .catalogue-sentinel{min-height:72px;display:grid;place-items:center;color:var(--muted);font-size:.82rem}.catalogue-sentinel.error{color:var(--danger)}
  .season-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:10px}.season-card{border:1px solid var(--border);border-radius:13px;background:#0c1018;padding:11px}.season-card label{display:flex;gap:8px;align-items:flex-start}.season-card strong{display:block}.media-pill{display:inline-flex;padding:4px 8px;border-radius:999px;background:rgba(124,92,255,.13);color:#c4b8ff;font-size:.7rem;font-weight:850;margin-right:6px}
</style>
<script>
  const catalogueState={
    movie:{page:1,totalPages:1,loading:false,query:'',collection:'popular',genre:'',yearFrom:'',yearTo:'',ratingFrom:'',ratingTo:'',seen:new Set(),scrollY:0},
    tv:{page:1,totalPages:1,loading:false,query:'',collection:'popular',genre:'',yearFrom:'',yearTo:'',ratingFrom:'',ratingTo:'',seen:new Set(),scrollY:0}
  };
  let browseMedia='movie';
  let catalogueObserver=null;

  const browseView=document.getElementById('browse-view');
  const searchForm=document.getElementById('search-form');
  if(browseView&&!document.getElementById('media-switch')){
    const hero=browseView.querySelector('.hero');
    hero.insertAdjacentHTML('afterend','<div class="media-switch" id="media-switch" role="tablist" aria-label="Browse media type"><button type="button" role="tab" class="active" data-media="movie" aria-selected="true">Movies</button><button type="button" role="tab" data-media="tv" aria-selected="false">TV Shows</button></div>');
  }
  const oldLoadMore=document.getElementById('load-more-area');
  if(oldLoadMore)oldLoadMore.remove();
  const moviesGrid=document.getElementById('movies');
  if(moviesGrid&&!document.getElementById('catalogue-sentinel'))moviesGrid.insertAdjacentHTML('afterend','<div id="catalogue-sentinel" class="catalogue-sentinel" aria-live="polite"></div>');

  function currentCatalogueState(){return catalogueState[browseMedia];}
  function rememberControls(){const s=currentCatalogueState();s.query=document.getElementById('search').value.trim();s.genre=document.getElementById('genre-filter').value;s.yearFrom=document.getElementById('year-from').value;s.yearTo=document.getElementById('year-to').value;s.ratingFrom=document.getElementById('rating-from').value;s.ratingTo=document.getElementById('rating-to').value;}
  function restoreControls(){const s=currentCatalogueState();document.getElementById('search').value=s.query;document.getElementById('genre-filter').value=s.genre;document.getElementById('year-from').value=s.yearFrom;document.getElementById('year-to').value=s.yearTo;document.getElementById('rating-from').value=s.ratingFrom;document.getElementById('rating-to').value=s.ratingTo;}
  function catalogueParams(page){const s=currentCatalogueState();const p=new URLSearchParams({page:String(page),collection:s.collection});if(s.query)p.set('query',s.query);if(s.genre)p.set('genre_id',s.genre);if(s.yearFrom)p.set('year_from',s.yearFrom);if(s.yearTo)p.set('year_to',s.yearTo);if(s.ratingFrom)p.set('rating_from',s.ratingFrom);if(s.ratingTo)p.set('rating_to',s.ratingTo);return p;}
  function tvCard(show){const poster=show.poster_url?`<img src="${esc(show.poster_url)}" alt="Poster for ${esc(show.name)}" loading="lazy">`:`<div class="no-poster">${esc(show.name)}</div>`;return `<button class="movie tv-card" data-tv-id="${show.tmdb_id}"><div class="poster">${poster}</div><div class="movie-title">${esc(show.name)}</div><div class="movie-meta"><span class="media-pill">TV</span>${esc(show.year||'')} · ★ ${Number(show.rating||0).toFixed(1)}</div></button>`;}
  function appendUnique(items,cardFn,idFn,reset=false){const s=currentCatalogueState();const container=document.getElementById('movies');if(reset){container.innerHTML='';s.seen.clear();}const html=[];for(const item of items){const id=String(idFn(item));if(s.seen.has(id))continue;s.seen.add(id);html.push(cardFn(item));}container.insertAdjacentHTML('beforeend',html.join(''));if(browseMedia==='movie')bindMovieCards(container);else bindTvCards(container);}
  function bindTvCards(container=document){container.querySelectorAll('[data-tv-id]').forEach(card=>{if(card.dataset.bound)return;card.dataset.bound='1';card.addEventListener('click',()=>openTv(Number(card.dataset.tvId),card));});}
  function updateSentinel(message='',error=false){const sentinel=document.getElementById('catalogue-sentinel');if(!sentinel)return;sentinel.textContent=message;sentinel.classList.toggle('error',error);}
  async function loadCataloguePage(page,{reset=false}={}){const s=currentCatalogueState();if(s.loading||page<1||(!reset&&page>s.totalPages))return;s.loading=true;updateSentinel(page>1?`Loading more ${browseMedia==='movie'?'movies':'TV shows'}…`:'Loading…');try{const endpoint=browseMedia==='movie'?'catalog/movies':'catalog/tv';const data=await api(`${endpoint}?${catalogueParams(page)}`);if(browseMedia==='movie'){appendUnique(data.movies||[],movieCard,item=>item.tmdb_id,reset);}else{appendUnique(data.shows||[],tvCard,item=>item.tmdb_id,reset);}s.page=Number(data.page||page);s.totalPages=Number(data.total_pages||1);document.getElementById('catalogue-title').textContent=browseMedia==='movie'?'Movies':'TV Shows';document.getElementById('catalogue-meta').textContent=`${Number(data.total_results||0).toLocaleString()} titles · page ${s.page} of ${s.totalPages}`;updateSentinel(s.page<s.totalPages?'Scroll for more':'');}catch(error){updateSentinel(`Could not load more ${browseMedia==='movie'?'movies':'TV shows'}. Scroll again to retry.`,true);if(reset)document.getElementById('movies').innerHTML=`<div class="empty">${esc(error.message)}</div>`;}finally{s.loading=false;}}

  function resetCatalogue(){const s=currentCatalogueState();rememberControls();s.page=1;s.totalPages=1;s.seen.clear();loadCataloguePage(1,{reset:true});}
  async function switchMedia(type){if(type===browseMedia)return;catalogueState[browseMedia].scrollY=window.scrollY;browseMedia=type;document.querySelectorAll('#media-switch [data-media]').forEach(btn=>{const active=btn.dataset.media===type;btn.classList.toggle('active',active);btn.setAttribute('aria-selected',active?'true':'false');});const search=document.getElementById('search');search.placeholder=type==='movie'?'Search movies, actors or titles':'Search TV shows by title';search.setAttribute('aria-label',type==='movie'?'Search movies':'Search TV shows');document.querySelector('.discovery-tools label:nth-child(2)').childNodes[0].textContent=type==='movie'?'Released from':'First aired from';document.querySelector('.discovery-tools label:nth-child(3)').childNodes[0].textContent=type==='movie'?'Released to':'First aired to';renderCollections();await loadGenresForMedia();restoreControls();await loadCataloguePage(currentCatalogueState().page||1,{reset:true});window.scrollTo({top:catalogueState[type].scrollY||0,behavior:'instant'});}
  function renderCollections(){const filters=document.getElementById('filters');const s=currentCatalogueState();const values=browseMedia==='movie'?[['popular','Popular'],['now_playing','Now playing'],['top_rated','Top rated'],['upcoming','Upcoming']]:[['popular','Popular'],['airing_today','Airing today'],['on_the_air','On TV'],['top_rated','Top rated']];filters.innerHTML=values.map(([value,label])=>`<button class="chip ${s.collection===value?'active':''}" data-collection="${value}">${label}</button>`).join('');filters.querySelectorAll('[data-collection]').forEach(btn=>btn.addEventListener('click',()=>{s.collection=btn.dataset.collection;filters.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===btn));resetCatalogue();}));}
  async function loadGenresForMedia(){try{const endpoint=browseMedia==='movie'?'catalog/genres':'catalog/tv/genres';const data=await api(endpoint);const select=document.getElementById('genre-filter');const current=currentCatalogueState().genre;select.innerHTML='<option value="">All genres</option>'+data.genres.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('');select.value=current;}catch(error){toast(error.message);}}
  document.querySelectorAll('#media-switch [data-media]').forEach(btn=>btn.addEventListener('click',()=>switchMedia(btn.dataset.media)));
  searchForm.addEventListener('submit',event=>{event.preventDefault();rememberControls();resetCatalogue();},{capture:true});
  ['genre-filter','year-from','year-to','rating-from','rating-to'].forEach(id=>document.getElementById(id)?.addEventListener('change',()=>{rememberControls();resetCatalogue();},{capture:true}));
  document.getElementById('clear-filters')?.addEventListener('click',()=>{const s=currentCatalogueState();s.genre='';s.yearFrom='';s.yearTo='';s.ratingFrom='';s.ratingTo='';restoreControls();resetCatalogue();},{capture:true});

  const sentinel=document.getElementById('catalogue-sentinel');if(sentinel){catalogueObserver=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting)){const s=currentCatalogueState();if(!s.loading&&s.page<s.totalPages)loadCataloguePage(s.page+1);}}, {rootMargin:'600px 0px'});catalogueObserver.observe(sentinel);}

  async function openTv(id,trigger){try{detailTrigger=trigger;state.movie=await api(`catalog/tv/${id}`);renderTvDetail(state.movie);document.getElementById('modal').classList.remove('hidden');document.getElementById('close-modal').focus();}catch(error){toast(error.message);}}
  function renderTvDetail(show){const genres=(show.genres||[]).map(g=>g.name).join(' · ');const seasons=(show.seasons||[]).map(season=>`<div class="season-card"><label><input type="checkbox" data-season-number="${season.season_number}"><span><strong>${esc(season.name)}</strong><span class="muted">${season.episode_count} episodes${season.air_date?` · ${esc(season.air_date)}`:''}</span></span></label></div>`).join('');const cast=(show.cast||[]).map(actor=>`<div class="cast-card">${actor.profile_url?`<img src="${esc(actor.profile_url)}" alt="${esc(actor.name)}">`:''}<div class="cast-name">${esc(actor.name)}</div><div class="cast-role">${esc(actor.character||'')}</div></div>`).join('');document.getElementById('detail').innerHTML=`<div class="detail-hero" style="${show.backdrop_url?`background-image:url('${esc(show.backdrop_url)}')`:''}"><div class="detail-copy"><div class="eyebrow">TV Show</div><h2>${esc(show.name)}</h2><div class="muted">${esc(show.year||'')} · ${show.number_of_seasons||0} seasons · ${show.number_of_episodes||0} episodes${show.certification?` · ${esc(show.certification)}`:''}</div><div class="actions"><button class="button primary" id="request-tv-series">Request entire series</button>${show.trailer_url?`<a class="button" href="${esc(show.trailer_url)}" target="_blank" rel="noopener noreferrer">Watch trailer</a>`:''}</div></div></div><div class="detail-body"><p class="muted">${esc(show.overview||'No synopsis is available.')}</p><div class="muted">${esc(genres)}</div>${show.creators?.length?`<div class="section-title">Created by</div><div>${show.creators.map(c=>esc(c.name)).join(', ')}</div>`:''}<div class="section-title">Seasons</div><div class="season-grid">${seasons}</div><div class="actions"><button class="button" id="request-tv-seasons">Request selected seasons</button></div>${cast?`<div class="section-title">Cast</div><div class="cast-strip">${cast}</div>`:''}</div>`;document.getElementById('request-tv-series').addEventListener('click',()=>submitTvRequest(show.tmdb_id,'series',[]));document.getElementById('request-tv-seasons').addEventListener('click',()=>submitTvRequest(show.tmdb_id,'seasons',[...document.querySelectorAll('[data-season-number]:checked')].map(x=>Number(x.dataset.seasonNumber))));}
  async function submitTvRequest(id,scope,seasons){try{const result=await api(`tv/${id}/request`,{method:'POST',body:JSON.stringify({scope,seasons})});toast(`${result.title} requested through Sonarr`);closeModal();loadDownloads();}catch(error){toast(error.message);}}

  const originalOpenDownloadDetails=openDownloadDetails;openDownloadDetails=async function(item,card){if(item.media_type==='tv'){try{detailTrigger=card;state.movie=await api(`downloads/tv/${item.id}/details`);renderTvDownloadDetail(state.movie);document.getElementById('modal').classList.remove('hidden');document.getElementById('close-modal').focus();}catch(error){toast(error.message);}return;}return originalOpenDownloadDetails(item,card);};
  function renderTvDownloadDetail(show){renderTvDetail(show);document.getElementById('request-tv-series')?.remove();document.getElementById('request-tv-seasons')?.remove();document.querySelectorAll('[data-season-number]').forEach(el=>el.disabled=true);const req=show.request||{};document.querySelector('#detail .detail-body').insertAdjacentHTML('afterbegin',`<div class="section-title">Request & library</div><div class="library-card"><div><span>Status</span>${esc(req.status_message||req.status||'')}</div><div><span>Requested by</span>${esc(req.requested_by||'')}</div><div><span>Scope</span>${esc(req.scope||'series')}</div><div><span>Episodes available</span>${Number(req.available_episode_count||0)} / ${Number(req.total_episode_count||0)}</div></div>`);}

  renderCollections();loadGenresForMedia();loadCataloguePage(1,{reset:true});
</script>
"""

if "media-switch" not in main.INDEX_HTML:
    main.INDEX_HTML = main.INDEX_HTML.replace("</body>", _TV_UI + "\n</body>")
